use crate::tty::{
    flush, output_mode, print_header, print_kv, print_kv_bold, print_section, print_warning,
    OutputMode,
};
use anyhow::Result;
use clap::Args as ClapArgs;
use crossterm::style::{Color, Stylize};
use first_plan_core::evolution::{
    analyze,
    deprecations::{ChangelogKind, Severity},
    migrations::BreakingKind,
    EvolutionReport,
};
use std::path::PathBuf;

#[derive(ClapArgs)]
pub struct Args {
    #[arg(long, default_value = ".")]
    pub root: PathBuf,

    #[arg(long)]
    pub output: Option<PathBuf>,

    #[arg(long)]
    pub json: bool,
}

pub fn run(args: Args) -> Result<()> {
    let mode = output_mode(args.json);
    let report = analyze(&args.root);

    let out_dir = args
        .output
        .clone()
        .unwrap_or_else(|| args.root.join(".first-plan").join("13-evolution"));

    std::fs::create_dir_all(&out_dir)?;
    std::fs::write(
        out_dir.join("00-deprecations.md"),
        render_deprecations_md(&report),
    )?;
    std::fs::write(
        out_dir.join("01-migrations.md"),
        render_migrations_md(&report),
    )?;
    std::fs::write(
        out_dir.join("02-replacements.md"),
        render_replacements_md(&report),
    )?;
    std::fs::write(out_dir.join("03-summary.md"), render_summary_md(&report))?;
    std::fs::write(
        out_dir.join("report.json"),
        serde_json::to_string_pretty(&report)?,
    )?;

    if mode == OutputMode::Json {
        println!("{}", serde_json::to_string_pretty(&report)?);
        return Ok(());
    }

    render_pretty(&report, &out_dir);
    Ok(())
}

fn render_pretty(report: &EvolutionReport, out_dir: &std::path::Path) {
    print_header(&format!("Evolution Layer ({}ms)", report.elapsed_ms));

    print_section("Deprecations");
    if report.deprecations.total == 0 {
        print_warning("Nenhuma depreciacao detectada");
    } else {
        print_kv_bold(
            "In-code markers",
            &report.deprecations.items.len().to_string(),
            Color::Yellow,
        );
        print_kv_bold(
            "CHANGELOG entries",
            &report.deprecations.changelog_deprecations.len().to_string(),
            Color::Yellow,
        );

        let critical: Vec<_> = report
            .deprecations
            .items
            .iter()
            .filter(|i| matches!(i.severity, Severity::Critical))
            .collect();
        if !critical.is_empty() {
            println!();
            println!("  {}", "Critical (com remove-after):".dim());
            for item in critical.iter().take(5) {
                println!(
                    "    {} {}:{} - {}",
                    "CRITICAL".with(Color::Red),
                    item.file.as_str().with(Color::Cyan),
                    item.line,
                    item.remove_after.as_deref().unwrap_or("?").bold()
                );
            }
        }
    }

    print_section("Migrations (git history)");
    if report.migrations.analyzed_commits == 0 {
        print_warning("Sem historia git suficiente");
    } else {
        print_kv(
            "Window",
            &format!("{} days", report.migrations.window_days),
            Color::DarkGrey,
        );
        print_kv(
            "Commits analisados",
            &report.migrations.analyzed_commits.to_string(),
            Color::DarkGrey,
        );
        print_kv_bold(
            "Breaking commits",
            &report.migrations.breaking_commits.len().to_string(),
            if report.migrations.breaking_commits.is_empty() {
                Color::Green
            } else {
                Color::Yellow
            },
        );
        print_kv_bold(
            "Replacement pairs",
            &report.migrations.replacement_candidates.len().to_string(),
            if report.migrations.replacement_candidates.is_empty() {
                Color::DarkGrey
            } else {
                Color::Cyan
            },
        );

        for bc in report.migrations.breaking_commits.iter().take(5) {
            let kind_str = format!("{:?}", bc.kind);
            println!(
                "  {} {} {} {}",
                &bc.sha[..7.min(bc.sha.len())]
                    .to_string()
                    .with(Color::DarkGrey),
                kind_str.as_str().with(Color::Yellow),
                bc.subject.as_str().bold(),
                format!("({} files)", bc.files_affected).dim()
            );
        }
    }

    println!();
    print_kv_bold("Saved to", &out_dir.to_string_lossy(), Color::Green);
    flush();
}

fn render_deprecations_md(report: &EvolutionReport) -> String {
    let mut s = String::new();
    s.push_str("# Deprecations\n\n");
    s.push_str(&format!(
        "Generated by `first-plan-engine evolution` at {}\n\n",
        report.generated_at
    ));

    if report.deprecations.items.is_empty() && report.deprecations.changelog_deprecations.is_empty()
    {
        s.push_str("Nenhuma depreciacao detectada. Buscas feitas:\n\n");
        s.push_str("- Comentarios @deprecated, DEPRECATED:, TODO(deprecate), TODO(remove-after)\n");
        s.push_str("- Rust `#[deprecated]`, Java `@Deprecated`, JS/TS `@deprecated` JSDoc\n");
        s.push_str("- CHANGELOG.md secoes Deprecated / Removed\n");
        return s;
    }

    if !report.deprecations.items.is_empty() {
        s.push_str(&format!(
            "## In-code markers ({})\n\n",
            report.deprecations.items.len()
        ));
        s.push_str("| Severity | File:Line | Marker | Replacement | Since | Remove after |\n");
        s.push_str("|----------|-----------|--------|-------------|-------|--------------|\n");
        for item in &report.deprecations.items {
            s.push_str(&format!(
                "| {:?} | `{}:{}` | {} | {} | {} | {} |\n",
                item.severity,
                item.file,
                item.line,
                item.marker,
                item.replacement.as_deref().unwrap_or("-"),
                item.since.as_deref().unwrap_or("-"),
                item.remove_after.as_deref().unwrap_or("-"),
            ));
        }
        s.push('\n');
    }

    if !report.deprecations.changelog_deprecations.is_empty() {
        s.push_str(&format!(
            "## CHANGELOG entries ({})\n\n",
            report.deprecations.changelog_deprecations.len()
        ));
        s.push_str("| Version | Kind | Text |\n");
        s.push_str("|---------|------|------|\n");
        for entry in &report.deprecations.changelog_deprecations {
            let kind_str = match entry.kind {
                ChangelogKind::Deprecated => "Deprecated",
                ChangelogKind::Removed => "Removed",
                ChangelogKind::Changed => "Changed/Breaking",
            };
            let text_short = if entry.text.len() > 120 {
                format!("{}...", &entry.text[..120])
            } else {
                entry.text.clone()
            };
            s.push_str(&format!(
                "| {} | {} | {} |\n",
                entry.version, kind_str, text_short
            ));
        }
        s.push('\n');
    }

    s.push_str("---\n\n");
    s.push_str("**Como usar**: AI nao deve sugerir padroes marcados aqui. `Critical` (com remove-after) sao prazo firme - se estamos perto da data, refactor prioritario. `Warning` (com replacement conhecido) - sempre usar o replacement em codigo novo.\n");
    s
}

fn render_migrations_md(report: &EvolutionReport) -> String {
    let mut s = String::new();
    s.push_str("# Migrations (Breaking Changes)\n\n");
    s.push_str(&format!(
        "Generated by `first-plan-engine evolution` at {}\n\n",
        report.generated_at
    ));

    if report.migrations.analyzed_commits == 0 {
        s.push_str("Sem historia git para minerar.\n");
        return s;
    }

    s.push_str(&format!(
        "Window: ultimos {} dias, {} commits analisados.\n\n",
        report.migrations.window_days, report.migrations.analyzed_commits
    ));

    if report.migrations.breaking_commits.is_empty() {
        s.push_str("Nenhum commit breaking detectado. Codebase estavel ou time nao usa marcadores convencionais (feat!, BREAKING CHANGE).\n");
        return s;
    }

    s.push_str(&format!(
        "## Breaking commits ({})\n\n",
        report.migrations.breaking_commits.len()
    ));
    s.push_str("Ordenado por recencia. Kind indica marcador que triggerou deteccao.\n\n");
    s.push_str("| SHA | Kind | Subject | Date | Files |\n");
    s.push_str("|-----|------|---------|------|-------|\n");
    for bc in &report.migrations.breaking_commits {
        let kind_str = match bc.kind {
            BreakingKind::ConventionalBreaking => "conventional!",
            BreakingKind::BreakingChangeFooter => "BREAKING CHANGE",
            BreakingKind::RefactorKeyword => "refactor",
            BreakingKind::MigrateKeyword => "migrate",
            BreakingKind::RewriteKeyword => "rewrite",
        };
        s.push_str(&format!(
            "| `{}` | {} | {} | {} | {} |\n",
            &bc.sha[..7.min(bc.sha.len())],
            kind_str,
            bc.subject,
            &bc.date[..10.min(bc.date.len())],
            bc.files_affected
        ));
    }
    s.push('\n');

    s.push_str("---\n\n");
    s.push_str("**Como usar**: commits breaking recentes sao sinal de que area do codigo esta em transicao. AI ao propor mudanca em area recem-migrada deve conferir se esta seguindo o padrao novo (ver `02-replacements.md`).\n");
    s
}

fn render_replacements_md(report: &EvolutionReport) -> String {
    let mut s = String::new();
    s.push_str("# Replacement Pairs\n\n");
    s.push_str(&format!(
        "Generated by `first-plan-engine evolution` at {}\n\n",
        report.generated_at
    ));

    if report.migrations.replacement_candidates.is_empty() {
        s.push_str(
            "Nenhum par (arquivo removido + arquivo adicionado com similaridade) detectado.\n",
        );
        return s;
    }

    s.push_str(&format!(
        "## Detected pairs ({})\n\n",
        report.migrations.replacement_candidates.len()
    ));
    s.push_str("Arquivos removidos + arquivos adicionados no mesmo commit com nome similar. Confidence baseada em stem match + mesmo diretorio.\n\n");
    s.push_str("| Confidence | Removed | Added | Commit | Subject |\n");
    s.push_str("|------------|---------|-------|--------|---------|\n");
    for pair in &report.migrations.replacement_candidates {
        s.push_str(&format!(
            "| {:.2} | `{}` | `{}` | `{}` | {} |\n",
            pair.confidence,
            pair.removed,
            pair.added,
            &pair.sha[..7.min(pair.sha.len())],
            pair.subject
        ));
    }
    s.push('\n');

    s.push_str("---\n\n");
    s.push_str("**Como usar**: se AI vai sugerir tocar `removed` file, verificar se replacement `added` tem o codigo que precisa. Padrao migrado historicamente reflete decisao do time - reverter sem contexto eh anti-padrao.\n");
    s
}

fn render_summary_md(report: &EvolutionReport) -> String {
    let mut s = String::new();
    s.push_str("# Evolution Summary\n\n");
    s.push_str(&format!(
        "Generated by `first-plan-engine evolution` at {}\n\n",
        report.generated_at
    ));

    let critical_count = report
        .deprecations
        .items
        .iter()
        .filter(|i| matches!(i.severity, Severity::Critical))
        .count();

    s.push_str("## Overview\n\n");
    s.push_str(&format!(
        "- Deprecations em codigo: {} (critical: {})\n",
        report.deprecations.items.len(),
        critical_count
    ));
    s.push_str(&format!(
        "- CHANGELOG deprecation entries: {}\n",
        report.deprecations.changelog_deprecations.len()
    ));
    s.push_str(&format!(
        "- Breaking commits (ultimos {} dias): {}\n",
        report.migrations.window_days,
        report.migrations.breaking_commits.len()
    ));
    s.push_str(&format!(
        "- Replacement pairs detectados: {}\n\n",
        report.migrations.replacement_candidates.len()
    ));

    if critical_count > 0 {
        s.push_str(&format!("## Actionable warnings ({})\n\n", critical_count));
        s.push_str("Itens com prazo de remocao definido. Refactor prioritario conforme se aproxima da data.\n\n");
        for item in report
            .deprecations
            .items
            .iter()
            .filter(|i| matches!(i.severity, Severity::Critical))
        {
            s.push_str(&format!(
                "- **{}:{}** - remove-after: `{}`{}\n",
                item.file,
                item.line,
                item.remove_after.as_deref().unwrap_or("?"),
                item.replacement
                    .as_ref()
                    .map(|r| format!(", use `{}`", r))
                    .unwrap_or_default()
            ));
        }
        s.push('\n');
    }

    s.push_str("---\n\n");
    s.push_str("**Como usar em Plan-First**: antes de propor mudanca, ler este summary. Nao sugerir padroes depreciados. Priorizar migrations que estao em andamento. Ver detalhe em `00-deprecations.md`, `01-migrations.md`, `02-replacements.md`.\n");
    s
}
