//! Tool-specific adapters that render IR context into per-tool format.

use anyhow::Result;
use std::path::{Path, PathBuf};
use tera::Context as TeraContext;

use super::{render_template, Adapter, AdapterInfo, IrContext};

pub fn all() -> Vec<Box<dyn Adapter>> {
    vec![
        Box::new(CodexAdapter),
        Box::new(CursorAdapter),
        Box::new(CopilotAdapter),
        Box::new(ClineAdapter),
        Box::new(GenericAdapter),
    ]
}

pub fn get(name: &str) -> Option<Box<dyn Adapter>> {
    all().into_iter().find(|a| a.name() == name)
}

fn build_tera_context(ir: &IrContext) -> TeraContext {
    let mut ctx = TeraContext::new();
    ctx.insert("project_name", &ir.project_name);
    ctx.insert("has_ir", &ir.has_ir);
    ctx.insert("sections", &ir.sections);
    ctx.insert("quick_glance", &ir.quick_glance);
    ctx.insert("stacks", &ir.stacks);
    ctx.insert("key_conventions", &ir.key_conventions);
    ctx.insert("reuse_summary", &ir.reuse_summary);
    ctx.insert("features_summary", &ir.features_summary);
    ctx.insert("quality_summary", &ir.quality_summary);
    ctx.insert("contracts_summary", &ir.contracts_summary);
    ctx.insert("evolution_summary", &ir.evolution_summary);
    ctx.insert("runtime_summary", &ir.runtime_summary);
    ctx
}

const HEADER_NOTE: &str =
    "<!-- Generated by first-plan-engine generate. Do not edit manually. Re-run to update. -->";

pub struct CodexAdapter;

impl Adapter for CodexAdapter {
    fn name(&self) -> &str {
        "codex"
    }
    fn info(&self) -> AdapterInfo {
        AdapterInfo {
            name: "codex".to_string(),
            description: "OpenAI Codex CLI, Cursor Chat via AGENTS.md, and any tool that reads AGENTS.md convention".to_string(),
            output_files: vec!["AGENTS.md".to_string()],
        }
    }
    fn render(&self, ir: &IrContext, output_base: &Path) -> Result<Vec<(PathBuf, String)>> {
        let ctx = build_tera_context(ir);
        let template = include_str!("../../../../../adapters/codex/AGENTS.md.tera");
        let content = render_template(template, &ctx)?;
        Ok(vec![(output_base.join("AGENTS.md"), content)])
    }
}

pub struct CursorAdapter;

impl Adapter for CursorAdapter {
    fn name(&self) -> &str {
        "cursor"
    }
    fn info(&self) -> AdapterInfo {
        AdapterInfo {
            name: "cursor".to_string(),
            description: "Cursor IDE - .cursorrules (legacy) + .cursor/rules/*.mdc (modern scoped)"
                .to_string(),
            output_files: vec![
                ".cursorrules".to_string(),
                ".cursor/rules/first-plan-context.mdc".to_string(),
            ],
        }
    }
    fn render(&self, ir: &IrContext, output_base: &Path) -> Result<Vec<(PathBuf, String)>> {
        let ctx = build_tera_context(ir);
        let legacy = include_str!("../../../../../adapters/cursor/cursorrules.tera");
        let modern = include_str!("../../../../../adapters/cursor/rules.mdc.tera");
        Ok(vec![
            (
                output_base.join(".cursorrules"),
                render_template(legacy, &ctx)?,
            ),
            (
                output_base.join(".cursor/rules/first-plan-context.mdc"),
                render_template(modern, &ctx)?,
            ),
        ])
    }
}

pub struct CopilotAdapter;

impl Adapter for CopilotAdapter {
    fn name(&self) -> &str {
        "copilot"
    }
    fn info(&self) -> AdapterInfo {
        AdapterInfo {
            name: "copilot".to_string(),
            description: "GitHub Copilot - .github/copilot-instructions.md".to_string(),
            output_files: vec![".github/copilot-instructions.md".to_string()],
        }
    }
    fn render(&self, ir: &IrContext, output_base: &Path) -> Result<Vec<(PathBuf, String)>> {
        let ctx = build_tera_context(ir);
        let template = include_str!("../../../../../adapters/copilot/copilot-instructions.md.tera");
        let content = render_template(template, &ctx)?;
        Ok(vec![(
            output_base.join(".github/copilot-instructions.md"),
            content,
        )])
    }
}

pub struct ClineAdapter;

impl Adapter for ClineAdapter {
    fn name(&self) -> &str {
        "cline"
    }
    fn info(&self) -> AdapterInfo {
        AdapterInfo {
            name: "cline".to_string(),
            description: "Cline VS Code extension - .clinerules".to_string(),
            output_files: vec![".clinerules".to_string()],
        }
    }
    fn render(&self, ir: &IrContext, output_base: &Path) -> Result<Vec<(PathBuf, String)>> {
        let ctx = build_tera_context(ir);
        let template = include_str!("../../../../../adapters/cline/clinerules.tera");
        let content = render_template(template, &ctx)?;
        Ok(vec![(output_base.join(".clinerules"), content)])
    }
}

pub struct GenericAdapter;

impl Adapter for GenericAdapter {
    fn name(&self) -> &str {
        "generic"
    }
    fn info(&self) -> AdapterInfo {
        AdapterInfo {
            name: "generic".to_string(),
            description: "Universal CONVENTIONS.md - works with Aider, Continue.dev and any tool that reads convention docs".to_string(),
            output_files: vec!["CONVENTIONS.md".to_string()],
        }
    }
    fn render(&self, ir: &IrContext, output_base: &Path) -> Result<Vec<(PathBuf, String)>> {
        let ctx = build_tera_context(ir);
        let template = include_str!("../../../../../adapters/generic/CONVENTIONS.md.tera");
        let content = render_template(template, &ctx)?;
        Ok(vec![(output_base.join("CONVENTIONS.md"), content)])
    }
}

#[allow(dead_code)]
fn header_note() -> &'static str {
    HEADER_NOTE
}
